# Generated by Django 5.2 on 2025-07-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
